I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /cm/shared/openmind/cuda/7.5/lib64:/cm/shared/openmind/cuda/7.5/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:2092] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
print sys.argv = ['main_nn.py', '2915977', '645', 'om_2x2_1_cosx1_plus_x2_depth2', 'task_2_August_HBF2_depth_2_1000_dont_train_S', 'HBF2_6_6_multiple_1000', 'True', '6,6', 'multiple_S', 'task_f2d_2x2_1_cosx1_plus_x2_depth2', 'False', 'False', 'hbf', 'data_trunc_norm_kern', 'dont_normalize', 'dont_train_S']
len(sys.argv) = 16
print argv = ['main_nn.py', '2915977', '645', 'om_2x2_1_cosx1_plus_x2_depth2', 'task_2_August_HBF2_depth_2_1000_dont_train_S', 'HBF2_6_6_multiple_1000', 'True', '6,6', 'multiple_S', 'task_f2d_2x2_1_cosx1_plus_x2_depth2', 'False', 'False', 'hbf', 'data_trunc_norm_kern', 'dont_normalize', 'dont_train_S']
len(argv) = 16
---------> len(argv) 16
['main_nn.py', '2915977', '645', 'om_2x2_1_cosx1_plus_x2_depth2', 'task_2_August_HBF2_depth_2_1000_dont_train_S', 'HBF2_6_6_multiple_1000', 'True', '6,6', 'multiple_S', 'task_f2d_2x2_1_cosx1_plus_x2_depth2', 'False', 'False', 'hbf', 'data_trunc_norm_kern', 'dont_normalize', 'dont_train_S']
2.8
mdl_type:  hbf
['main_nn.py', '2915977', '645', 'om_2x2_1_cosx1_plus_x2_depth2', 'task_2_August_HBF2_depth_2_1000_dont_train_S', 'HBF2_6_6_multiple_1000', 'True', '6,6', 'multiple_S', 'task_f2d_2x2_1_cosx1_plus_x2_depth2', 'False', 'False', 'hbf', 'data_trunc_norm_kern', 'dont_normalize', 'dont_train_S']
use_tensorboard False
experiment_root_dir=om_2x2_1_cosx1_plus_x2_depth2,slurm_jobid=2915977,slurm_array_task_id=645,job_name=HBF2_6_6_multiple_1000
----====> TASK NAME: task_f2d_2x2_1_cosx1_plus_x2_depth2
---> task_name:  task_f2d_2x2_1_cosx1_plus_x2_depth2
(N_train,D) =  (60025, 2)
(N_test,D_out) =  (60025, 1)
CLUSTER:  OM7
++> S/b_init  [None, 0.4177551, 1.6168164700331593]
++++> M (batch size) : 17000
++> starter_learning_rate  0.0270281133684
++> decay_rate  0.753699274236
++> decay_steps  7976
++> staircase  True
-----> Running model: hbf. (nb_hidden_layers = 2, nb_layers = 3)
-----> Units: [2, 6, 6, 1])
train_S_type:  multiple_S
data_trunc_norm_kern
6.44939087434
DONE INITILIZING
[None, <tf.Tensor 'Const:0' shape=(2, 6) dtype=float64>, <tf.Tensor 'truncated_normal:0' shape=(6, 6) dtype=float64>]
isinstance
--> init_S:  Tensor("Const_1:0", shape=(6,), dtype=float64)
--> trainable_S:  False
isinstance
--> init_S:  Tensor("Const_2:0", shape=(6,), dtype=float64)
--> trainable_S:  False
Traceback (most recent call last):
  File "main_nn.py", line 319, in <module>
    tf.gfile.DeleteRecursively('/tmp/mdl_logs')
  File "/home/brando90/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/gfile.py", line 352, in DeleteRecursively
    shutil.rmtree(path)
  File "/home/brando90/envs/tensorflow/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/brando90/envs/tensorflow/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/mdl_logs'
